### ISSUE TITLE
Transport close method

### ISSUE THREAD

**Issue by mewebstudio** [BrijeshBumrela/mediasoup-demo-server#1]
Thanks for sharing.
Is there a use method for transport close? How can do this with https://github.com/BrijeshBumrela/mediasoup-demo-ui?

**Comment by BrijeshBumrela** [comment]
Yes. If you are using framework specific router in frontend (react-router, ngRouter) and moving to different page, the webrtc connections might still persist. It would be better to close the connection before navigating.

This is just a demo single page, so I didn't implement. I may add that thing on weekend

**Comment by mewebstudio** [comment]
Thank you very much, your work very nice.

The user may want to turn the stream off instead of stopping it. It may want to turn off screen sharing and camera in particular.

Can you also improve on screen sharing?

**Comment by BrijeshBumrela** [comment]
yes sure. I'll try to implement screen sharing

**Comment by mewebstudio** [comment]
Thank you so much!

**Comment by BrijeshBumrela** [comment]
Hi @mewebstudio. Sorry I couldn't get back quickly. I've updated the code to include screen share as well as transport close functionality. But, there is weird bug with React's video ref thingy. I'm trying to figure that out. Meanwhile you can have a look at the implementation.

**Comment by mewebstudio** [comment]
Thank you for the development.
